// <auto-generated />
namespace CornerStoneApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmigration42018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigration42018));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200608207_add-migration 42018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
