// <auto-generated />
namespace CornerStoneApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class clientGood5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientGood5));
        
        string IMigrationMetadata.Id
        {
            get { return "201803290628343_clientGood5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
